include: package:surf_lint_rules/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
