name: flutter_external_accessory
description: Plugin for communicate with external accessory devices.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  surf_lint_rules: ^1.5.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterExternalAccessoryPlugin
